version: '3'

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: upload_production_django
    platform: linux/x86_64
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  pgbouncer:
    image: edoburu/pgbouncer:1.14.0
    restart: always
    environment:
      - DATABASE_URL=postgres://GVRFlLmcCNfGLhsFvSnCioYOPJPYpyfj:DAkWfpsnPHcAxMeQk2QmPOIZuz4BXG5qGFWi2hCCQE6kvndJHTuzz8SjnxOJY5qj@postgres/core
      - MAX_CLIENT_CONN=100
    ports:
      - 6434:5432
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: upload_production_postgres
    volumes:
      - ../scms_data/data_prod:/var/lib/postgresql/data:Z
      - ../scms_data/data_prod_backup:/backups:z
    env_file:
      - ./.envs/.production/.postgres

  mongo:
    image: mongo
    container_name: upload_production_mongo
    restart: always
    user: mongodb
    hostname: mongo
    volumes:
      - ../scms_data/mongo:/data/db
    ports:
        - "27017:27017"

  redis:
    image: redis:6

  celeryworker:
    <<: *django
    image: upload_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: upload_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: upload_production_flower
    command: /start-flower
